### ISSUE TITLE
Can no longer wear an outfit?

### ISSUE THREAD

**Issue by Python1320** [Metastruct/outfitter#1]
But could before?

Go to settings tab and press clear blacklist. 

This is a known bug/safeguard against bad addons, but it is hyperactive. We are working on fixing it.

**Comment by legomax** [comment]
Same problem here in server

When i press clear blacklist 

The console prints "unknown command"

Thats all and no longer wear outfits before wearable

At least i hope developement should be make

Manualy remove crash models and re download

**Comment by Python1320** [comment]
Crash safeguard has been lifted in dev version on next update to workshop.
