### ISSUE TITLE
Playermodel stop working

### ISSUE THREAD

**Issue by JohnOakman** [Metastruct/outfitter#10]
So yesterday, I downloaded a playermodel from the workshop, the first time I used it, it worked perfectly well.
Today, I can a million times if I want, it just prints an error : 

EnforceModel CRASH models/player/bobert/mkxcassie.mdl 468972568
DoChangeOutfit Setting model failed, but file.Existed crash models/player/bobert/mkxcassie.mdl

Many of my players also got this error sometimes. 
How can I fix it ?

**Comment by Python1320** [comment]
the model has crashed players while mounting so it was disabled to prevent further trolling with it. I will need to disable the blacklist for now.
