### ISSUE TITLE
Workshop addon 2861986932 has no valid playermodels

### ISSUE THREAD

**Issue by Tontonmayo** [Metastruct/outfitter#100]
![Garrysmod Screenshot 2024 07 21 - 01 31 33 92](https://github.com/user-attachments/assets/c5006914-4cdf-4783-ad76-9378c6945eb2)

[Custom Chat] Failed to fetch avatar for 76561199671387077: Missing avatar URL from the XML data
[Outfitter ERROR] Workshop addon 2861986932 has no valid playermodels
[Outfitter ERROR] Ori Arms ( questing crusader, Ori, Arms ):arms
[Outfitter ERROR] Ori Body ( questing crusader, Ori, Ori ):arms
[Outfitter ERROR] Ori Canon Body ( questing crusader, Ori, Ori ):arms

**Comment by sr229** [comment]
This is because you compiled your model incorrectly that Outfitter thinks there's no valid models. Do consult how to create playermodels so you have an idea how to make a playermodel, otherwise, this is not a valid report.
