### ISSUE TITLE
strange frame rate 

### ISSUE THREAD

**Issue by pumab** [Metastruct/outfitter#13]
https://www.youtube.com/watch?v=NBqmVIBsIE4&feature=youtu.be

**Comment by pumab** [comment]
the problem is probably on my side since I do not experience this on meta

**Comment by pumab** [comment]
So im posting network part of my servers cfg

sv_minrate		197010
sv_maxrate		0
sv_maxupdaterate 16
sv_maxcmdrate 16
sv_mincmdrate 16
sv_minupdaterate 16
decalfrequency		10
net_splitpacket_maxrate	1048576
mp_flashlight 1
sv_allowupload 0
sv_allowdownload 0

**Comment by SpiralP** [comment]
I've found a fullupdate fixes this

**Comment by Python1320** [comment]
Video was removed, I believe I know what you are talking about and it seems hard to fix it without doing a fullupdate. I might add a button to force yet one more fullupdate.

**Comment by Python1320** [comment]
This may have been solved on development version. Uploading to workshop soon.
