### ISSUE TITLE
Settings, history, and favorites tab missing

### ISSUE THREAD

**Issue by s980845** [Metastruct/outfitter#14]
I have the submit button and add to workshop button but the rest is missing

**Comment by SpiralP** [comment]
you have to either resize the window bigger, or click the maximize button next to the close button

![image](https://user-images.githubusercontent.com/2898730/30088661-9b0875fa-925c-11e7-84d5-d6a5c28ac9d3.png)

**Comment by s980845** [comment]
Ohhh thanks :)

**Comment by notcake** [comment]
wow such intuitive ux
