### ISSUE TITLE
Outfitter doesn't show anywhere in context menu?

### ISSUE THREAD

**Issue by melody2552** [Metastruct/outfitter#16]
In the official Meta Construct server I could use Outfitter perfectly fine but in every other server I went to, I was unable to even see Outfitter in the context menu let alone use it?

**Comment by bjoern90** [comment]
make sure the server has the addon or it wont work

**Comment by Python1320** [comment]
This addon is clientside, but it is required on the server to work fully or to show up at all.
 You can load it manually, but this is not supported and may not work at all.
