### ISSUE TITLE
"Too many verts, decals on model might cause crashes, use r_drawmodeldecals 0 to avoid this.."

### ISSUE THREAD

**Issue by cocofeliciano** [Metastruct/outfitter#18]
So there is this new playermodel that came out yesterday and I've been wanting to try it out with Outfitter on Meta Construct #1 but it suddenly gave me this:

[**Outfitter] CheckVVD	ValidateVVDVerts	models/player/dewobedil/danganronpa/ibuki_mioda/default_e	too many verts, decals on model might cause crashes, use r_drawmodeldecals 0 to avoid this	63399
[Outfitter] CheckVVD	ValidateVVDVerts	models/player/dewobedil/danganronpa/ibuki_mioda/default_f	too many verts, decals on model might cause crashes, use r_drawmodeldecals 0 to avoid this	63399
[Outfitter] CheckVVD	ValidateVVDVerts	models/player/dewobedil/danganronpa/ibuki_mioda/default_p	too many verts, decals on model might cause crashes, use r_drawmodeldecals 0 to avoid this	63399
[Outfitter] GMAPlayerModels	cache/workshop/924794017162576952.cache	0	0	1
[Outfitter] GMABlacklist	cache/workshop/924794017162576952.cache	
UIChoseWorkshop GMAPlayerModels 1255982644 no models!?**

If you can really help me how to fix this I would greatly apperciate it. I hope you get this soon!

**Comment by bjoern90** [comment]
i guess the outfitter might not work on a mix of npc and playermodel workshop

**Comment by cocofeliciano** [comment]
Why is that? Do you know?

**Comment by bjoern90** [comment]
idfk. im guesing

**Comment by Python1320** [comment]
Typing in console "outfitter_unsafe 1" will soon solve this, but this means you will be prone to crashes. There is a solution which is to disable the material decals or run "r_drawmodeldecals 0", but outfitter does not check this yet.

**Comment by cocofeliciano** [comment]
Thank you so much Python

**Comment by Python1320** [comment]
Fixed in new GMod
