### ISSUE TITLE
How to restrict this addon per groups?

### ISSUE THREAD

**Issue by LNATIC** [Metastruct/outfitter#2]
Hey there, so I need to do this on my server with this great addon. I have this code (something easy) but I just need to find the right outfitter's lua script to apply this code.

```
local allowedgroups = {
"owner",
"superadmin",
"admin",
"mod",
"vip3",
"vip2",
}

if (table.HasValue(allowedgroups, ply:GetUserGroup())) then
	--code code code...
else
        ply:SendLua("GAMEMODE:AddNotify(\"You have no access to this addon!\",NOTIFY_ERROR, 5)")
end
```

**Comment by EgrOnWire** [comment]
We will wrap permissions in our special system, all would be done through hooks.

**Comment by LNATIC** [comment]
Yeah you mean like PAC Editor system, but for now where I need to put this code? Thanks for responding!

**Comment by NotBudds** [comment]
Sorry if this is Necroposting, but does anyone have an ETA for the ULX restriction feature? I'd love to add it to my Donation package on my server.

**Comment by Noiwex** [comment]
DIY

**Comment by NotBudds** [comment]
I must admit, i'm not very gifted in LUA, I have scanned much of the script and understood very little. Just asking if anyone has indeed 'Done it themselves' and created a functioning ULX restriction workaround for the time that the official feature is being developed.

**Comment by KabusIblis** [comment]
If you want to charge money for a free accessory for servers, shouldn't you make a restriction system yourself?

**Comment by LNATIC** [comment]
Don't worry, I already made it.

**Comment by pumab** [comment]
@LNATIC Can I contact you somehow?
