### ISSUE TITLE
hi me help 

### ISSUE THREAD

**Issue by genrihx2** [Metastruct/outfitter#20]
me problems  crash  Players Outfitter Bodygroups  

			my server  complaints Players crash from server (Crashed/Network problem
			
			
addons/outfitter/lua/includes/modules/sqlext.lua:79: database disk image is malformed (Query: CREATE TABLE 'urlimage' (			`url`		TEXT NOT NULL CHECK(url <> '') UNIQUE,
			`ext`		TEXT NOT NULL CHECK(ext = 'vtf' OR ext = 'png' OR ext = 'jpg'),
			`last_used`	INTEGER NOT NULL DEFAULT 0,
			`fetched`	INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int) - 1477777422),
			`locked`	BOOLEAN NOT NULL DEFAULT 1,
			`w`			INTEGER(2) NOT NULL DEFAULT 0,
			`h`			INTEGER(2) NOT NULL DEFAULT 0,
			`fileid`	INTEG

**Comment by PotcFdk** [comment]
Your database seems to be corrupt. Try [this](https://sysinfotools.com/blog/fix-error-sqlite-database-disk-image-malformed/).

**Comment by genrihx2** [comment]
good  working  Thank  PotcFdk
