### ISSUE TITLE
Script errors when trying to equip a playermodel

### ISSUE THREAD

**Issue by Mofker** [Metastruct/outfitter#23]
I'm getting the following script errors when trying to equip any playermodel

[ERROR] lua/autorun/client/net_playervars.lua:132: attempt to call field 'queuesingle' (a nil value)
1. SetNetData - lua/autorun/client/net_playervars.lua:132
2. NetworkOutfit - lua/outfitter/net.lua:17
3. BroadcastMyOutfit - lua/outfitter/cl.lua:244
4. UIBroadcastMyOutfit - lua/outfitter/ui.lua:321
5. GUIBroadcastMyOutfit - lua/outfitter/gui.lua:688
6. DoClick - lua/outfitter/gui.lua:597
7. unknown - lua/vgui/dlabel.lua:232

**Comment by Python1320** [comment]
Cannot reproduce
