### ISSUE TITLE
Body Groups are seemingly broke (Workshop only?)

### ISSUE THREAD

**Issue by Codingale** [Metastruct/outfitter#24]
I was on metastruct earlier and had the body groups working ( I think ) and went to do it in Single Player but found out it didn't work.

Also, the dev branch is missing module folders etc, was going to see if I could help or something but it's seeming bare.

```
[ERROR] addons/outfitter/lua/outfitter/ui.lua:218: attempt to index local 'line' (a nil value)
  1. unknown - addons/outfitter/lua/outfitter/ui.lua:218
   2. unknown - lua/includes/modules/concommand.lua:54
```

**Comment by Python1320** [comment]
You will need to install npm and run the npm install command to get the dependencies! Thanks for the offer to help. I will take a look at some point, but singleplayer is mostly not supported right now. Listen server works better at the moment. Singleplayer would be trivial to implement, but I did not think anyone would use this for that purpose...
