### ISSUE TITLE
Outfitter Bodygroups.

### ISSUE THREAD

**Issue by drmgh** [Metastruct/outfitter#27]
I don't know if this issue has been dealt with, but I have problem on server with Outfitter Bodygroups. Everytime somebody tries to change bodygroup they get ERROR message.

> [ERROR] addons/outfitter/lua/outfitter/ui.lua:218: attempt to index local 'line' (a nil value)
>   1. unknown - addons/outfitter/lua/outfitter/ui.lua:218
>    2. unknown - lua/includes/modules/concommand.lua:54

This is message without DLib. When DLib is installed on server players get this message:

> [ERROR] addons/outfitter/lua/outfitter/ui.lua:218: attempt to index field "Trim" of a nil value (probably line?)
>   1. error - [C]:-1
>    2. __index - lua/dlib/core/funclib.lua:50
>     3. unknown - addons/outfitter/lua/outfitter/ui.lua:218
>      4. unknown - lua/includes/modules/concommand.lua:54

Can somebody tell me if there is way to fix this problem or that somebody is working on fix to that problem?

**Comment by Python1320** [comment]
Something is messing with concommand module, cannot fix
