### ISSUE TITLE
Syncing Issues

### ISSUE THREAD

**Issue by Ameno-Sagiri** [Metastruct/outfitter#3]
I understand this is fairly early in its planned development. Just wanted to point out the syncing is nearly non-existent with this. Seems like it only tries once, wouldn't it make more sense to write the outfit to something and have it constantly sync up every 15-30 seconds if it's not currently loaded on a client? Also, !outfit send doesn't seem to actually do anything. When we have syncing issues it never works. This is also reminiscent of PAC, PAC does the same thing as outfitter with these syncing problems, it's just not as common it seems.

Me and 6 people were testing this all morning on a sandbox server with PAC and whatnot. Outfits like to constantly and randomly unwear for random people. For instance, sometimes you can wear an outfit and send it directly in front of someone, and they won't see it, but the person standing next to them will see it.

Every time I go into first person for awhile and back to third, it will unwear for me on my screen only. 

Every time I encountered one of my friends on the server, his outfit would always be gone. The only way to fix it was for him to completely unwear it, and to go back into the workshop and find it again from step 1.

Great job on outfitter regardless, I will likely be getting back into rigging just for the purpose of using models I want instead of cutting up OBJs for PAC.

**Comment by EgrOnWire** [comment]
It is syncd through NetData module. If youre having troubles with your models, there must be a bug or PAC3 incompatibility. We'll look into that.

**Comment by bizzclaw** [comment]
What sort of insurance is there for players who don't initially receive the variables being updated?
Are you leaving that all up to the NetData Library?

**Comment by Python1320** [comment]
We may be missing something vital from metastruct that outfitter should have that causes this behaviour. I will try to look into it.

**Comment by Python1320** [comment]
I could reproduce, we applied an update. Do tell how well it works now!

**Comment by Python1320** [comment]
I guess it started working
