### ISSUE TITLE
Error by open it 

### ISSUE THREAD

**Issue by E2Ghibli** [Metastruct/outfitter#31]
When i spawn and click on it is comes but only one time the next time not but when i rejoin the server it come 

Player [1][E2 Ghibli] ERR: addons/outfitter/lua/includes/modules/urlimage.lua:90: attempt to index upvalue 'db' (a number value)
  1. __index - addons/notagain/lua/notagain/essential/autorun/lua_error_hook.lua:6
   2. get_record - addons/outfitter/lua/includes/modules/urlimage.lua:90
    3. GetURLImage - addons/outfitter/lua/includes/modules/urlimage.lua:311
     4. URLImage - addons/outfitter/lua/includes/modules/urlimage.lua:395
      5. xmashat - addons/outfitter/lua/outfitter/skin.lua:19
       6. SkinHook - addons/outfitter/lua/outfitter/skin.lua:66
        7. unknown - lua/vgui/dframe.lua:203

**Comment by notcake** [comment]
I'm sorry for your loss

**Comment by Python1320** [comment]
This error should be non fatal.

your garrysmod client database might be corrupt. Rename garrysmod/cl.db and try again.
