### ISSUE TITLE
Incompatibility with Legs3

### ISSUE THREAD

**Issue by Chillstice** [Metastruct/outfitter#32]
Love this project. I'm just going to post some issues regarding incompatibility with a few other player model related addons/ appearances. 

### Legs3
[Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=112806637)

Gmod Legs 3 adds first-person leg models so when you look down in-game you can see your legs. It's simple, elegant, and helps with immersion.
With Outfitter, players just see their legs represented as their last applied vanilla model using gmod's player model selector. I think the issue is that the legs mod is referencing server content for player models and I'm not entirely sure if Outfitter installs the player model addons server-side or if it's just client-side.
Either way I would love to see outfitter become compatible with Legs3.

**Comment by Chillstice** [comment]
I'm pretty sure this has been fixed by the Legs3 devs because it's working now.

**Comment by Python1320** [comment]
Will check what they did.
