### ISSUE TITLE
Incompatible with complex playermodel addons (required base-packs)

### ISSUE THREAD

**Issue by Chillstice** [Metastruct/outfitter#34]
Love this project. I'm just going to post some issues regarding incompatibility with a few other player model related addons/ appearances. 

There are a few player model packs on the workshop - some are developed by one of my friends. These playermodel packs require other base-packs to be subscribed to as a prerequisite. Example:

[Universal Sangheili Playermodel || Base](https://steamcommunity.com/sharedfiles/filedetails/?id=1550974781)
[USP || Halo 3](https://steamcommunity.com/sharedfiles/filedetails/?id=1550978039)
[USP || Halo: Reach](https://steamcommunity.com/sharedfiles/filedetails/?id=1550978639)

Perhaps there can be an option to load multiple addons one at a time through Outfitter.

**Comment by Python1320** [comment]
Dependencies are still not supported unfortunately, but are in the works
