### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by ClumsyYT** [Metastruct/outfitter#35]
Is there anyway to make this whitelist only?

**Comment by Cynosphere** [comment]
Elaborate? Do you mean based on addon, users, custom hook check, etc?

**Comment by ClumsyYT** [comment]
Pretty much is there a way I can restrict outfitter to people that buy my package from my donation addon. Tbh I don't care if I have to add there steamid to a file and whitelist it that way

**Comment by AgeOfPlain** [comment]
Any way to do this would be great! We can't use outfitter as some people get competitive about player models so we are looking to make this donor only to prevent abuse.

**Comment by Qinetti** [comment]
Any word on if there is an option to whitelist certain groups?

**Comment by Cynosphere** [comment]
There's undocumented hooks for restrictions. Untested code.
```lua
hook.Add("CanOutfit","DonorRestriction",function(ply,mdl,wsid)
    if ply:GetUserGroup() ~= "donor" or not ply:IsAdmin() or not ply:IsSuperAdmin() then
        -- feel free to add a message here or something to send to the player via ply:ChatPrint or something
        return false
    end
end
```
