### ISSUE TITLE
Client side Invisible Multiplayer Playermodels

### ISSUE THREAD

**Issue by TitusStudiosMediaGroup** [Metastruct/outfitter#37]
# Issue: Client side Invisible Multiplayer Playermodels

I have had this ongoing issue for a fair while now, on every server that I play on that has Outfitter mounted. I have never be able to get it working after 2 reinstalls of Garry's Mod and numerous unsubscribe and resubscribes of the addon.

## The Issue

Basically, On every server I go on, No matter what model. Outfitter works for on my playermodel *(and everyone else can see it too)*
But I can not see other players outfits - They go invisible. While the player is still there and you can see their Name & Health but there playermodel is completely gone.

#### With Outfitter Disabled:
![With Outfitter Disabled](https://i.imgur.com/yvMbqpq.jpg)

#### With Outfitter Enabled:
![With Outfitter Enabled](https://i.imgur.com/lnwVfuZ.jpg)

_This Happens no matter what playermodel is selected or being used. And if it is worn before with it disabled or enabled._

## Adding On
I have not gotten any Lua issues or warning in console from Outfitter, while downloading, loading, or seeing people with Outfitter enabled and wearing some playermodel.

# How I have tried to Fix it *(and failed)*
Currently all I have done is:
* Uninstalled my game twice - And Reinstalled it after one restart.
I have unsubscribed and closed my game, opened it until it fully un-mounts from my system directory. Closed my game and restarted my PC shortly after. And then doing it in reverse for installing & re-mounting.
* Done a full Garry's Mod File System Integrity Check (*Plus a full CRC Check*)
* Deleted the config files related to the addon, and downloaded them again.
* Deleted the workshop cache files

# Conclusion
**In conclusion,** this would be an excellent fix for the few people I know who have also experienced this issue - and the few who it still continues to this day. As I'm staff on a few Garry's Mod servers these days with Outfitter Installed, and I need to keep an eye on people who "Minge" around. And with the mass use of it on our servers it would help others and I to be able to see people and what they really what people to see themselves as - try not to see that as stupidly weird.

# How To Contact Me
If a possible fix on my side is found, if I'm just stupid and forgot to install or setup something, or if this is a bug and if it needs to be fixed *(I would like to know what was the problem was if its a bug, As I do a fair bit of Lua myself)*

### Contact Me Thru
* [Github](https://github.com/TitusStudiosMediaGroup)
* [Steam](https://steamcommunity.com/id/TitusStudiosMediaGroup/)
* [Twitter](https://twitter.com/TitusStudiosMG)
* [Website](https://titusstudiosmediagroup.github.io/)
* In the Comments of this *(Best Option for me)*

## Changelog

[16/04/19] Made the original post. Issue not fixed yet.
[17/04/19] Updated the post with trying to remove workshop cache. *(Didn't work)*

**Comment by Cynosphere** [comment]
- clear garrysmod/cache/workshop
- ensure the playermodel isnt just an invisible one to begin with

**Comment by TitusStudiosMediaGroup** [comment]
Hi! Thanks for helping. Sadly trying this did not work. Will be updating the post.

**Comment by Python1320** [comment]
Cannot reproduce. Please provide console debug log with "outfitter_dbg 10" console command set. Do you have Intel GPU? It is known to have problems.

**Comment by TitusStudiosMediaGroup** [comment]
Hi. No I have an Intel CPU and a Nvidia GPU. Problem resolved after reinstalling gmod.
