### ISSUE TITLE
Outfitter reloading user's pac while they are editting causes loss of unsaved work

### ISSUE THREAD

**Issue by thegrb93** [Metastruct/outfitter#39]
https://github.com/CapsAdmin/pac3/issues/799

**Comment by Python1320** [comment]
Is this still a problem?

**Comment by thegrb93** [comment]
I don't use pac enought to know, but it was never addressed in pac3's source. idk about outfitter's source.

**Comment by Python1320** [comment]
Outfitter no longer does fullupdates so this should not be an issue anymore.

**Comment by thegrb93** [comment]
Should do a quick test to be sure.

**Comment by Techbot121** [comment]
I have not noticed this happening anymore
