### ISSUE TITLE
Bugs in Murder.

### ISSUE THREAD

**Issue by ThatCrazyGuy** [Metastruct/outfitter#4]
In Murder playermodels glitch out in the camera and show a distorted default model distorted, but in-game the model is fine. When a player is killed the playermodel ragdoll defaults to the standard murder playermodels.

For some reason I can't select a distance mode it just reverts to Automatic when I select enabled or disabled.

**Comment by edunad** [comment]
"When a player is killed the playermodel ragdoll defaults to the standard murder playermodels."
The gamemode might be overwriting the player model on respawn (not sure tough).

**Comment by Noiwex** [comment]
It's not supposed to work in this gamemode. If you wish so, you can submit a pull request with a fix to the main repo.
