### ISSUE TITLE
Certain playermodels on the steam workshop are not compatible with outfitter.

### ISSUE THREAD

**Issue by LaurenceKw** [Metastruct/outfitter#43]
https://steamcommunity.com/sharedfiles/filedetails/?id=908040809
https://steamcommunity.com/sharedfiles/filedetails/?id=781302149
When attempting to load the outfit into the game, outfitter states that the mod has no playermodels.

**Comment by Python1320** [comment]
[Outfitter ERROR] Emilia ( maximo, Rezero ):Model is too complex (too many vertexes). Shooting the player could cause others to crash (Can use r_drawmodeldecals 0 to avoid this).

I am aware and the new gmod should no longer have this crashing so I will likely lift this restriction.
