### ISSUE TITLE
Outfitter causes demo recording for players

### ISSUE THREAD

**Issue by CRONKDONK** [Metastruct/outfitter#44]
Anytime I join, or anyone on my server joins, Outfitter causes REC to pop up on the top right, indicating that a demo has started recording. 
Here's a list of the servers addons:
https://steamcommunity.com/sharedfiles/filedetails/?id=1866831974
Please help find a fix to this issue, I want people to play without problems.

**Comment by Python1320** [comment]
If you have a way to trigger cl_fullupdate without invoking demo recording I cannot fix this. Outfitter requires a fullupdate hack right now unfortunately, otherwise the animations on the models won't work right.
