### ISSUE TITLE
Icons in history turn into texture errors after a server restart

### ISSUE THREAD

**Issue by awesomeiron9** [Metastruct/outfitter#45]
Everytime my favorite server restarts, my history icons transform into texture errors.

**Comment by Python1320** [comment]
This is a GMod bug most likely, but I will take a look

**Comment by GJungle1** [comment]
![mfGIoU8](https://user-images.githubusercontent.com/54341728/124033401-bdfddd00-d9ae-11eb-88ff-2c2b5ef20a58.png)

**Comment by Python1320** [comment]
Cannot reproduce. Haven't received a similar error report. Can be related to texture unloading if you alt tab.
