### ISSUE TITLE
Loaded workshop model 127781005 and now the addon no longer works at all

### ISSUE THREAD

**Issue by MrCodingFan** [Metastruct/outfitter#47]
Loaded: https://steamcommunity.com/sharedfiles/filedetails/?id=1277810054&searchtext=thinking+nut
After loading, my playermodel stayed a default GMod skin, though other players reported seeing me as the proper model I selected. No other models worked either at this point, and I could not see anyone else's models. Autowear is always on as well, clicking it will just tell me it is on.

**Comment by Python1320** [comment]
Please provide full debug output from console and reopen the issue, after running "outfitter_dbg 10" and rejoining
