### ISSUE TITLE
Can't see my own outfit

### ISSUE THREAD

**Issue by CastleArcade** [Metastruct/outfitter#50]
I was in a server that has this feature and I can see everyone's player models that they picked and that works fine, but I can't see my own when I use it.

**Comment by CastleArcade** [comment]
Just to add, I tested it on my own private server and it seemed to work fine. Nobody else seems to be having this issue, so I'm just wondering if it's some kind of file I need?

**Comment by Python1320** [comment]
Try deleting cl.db from garrysmod folder (make a backup!). Otherwise, please reopen issue with full console log with outfitter_dbg set to 10
