### ISSUE TITLE
"Web Browser" opening simultaneously with context menu toggle

### ISSUE THREAD

**Issue by hardyspaceresident** [Metastruct/outfitter#52]
A "Web Browser" window opens when I press my context menu toggle key. It appears under the context menu, pressing the key (my key is F1) once more closes the context menu but not the web browser. The window can be used for navigation. Both windows close if the escape key is pressed (Garry's Mod menu key.) It will be brought to the front if clicked from under the context menu. It can be jarring for some people who often use the context menu key, especially for actions "in a pinch."

The browser:
<img src="https://i.gyazo.com/ae72077621b5f38b71317140fe7cd2f8.png" alt="web browser"> </img>

It works:
<img src="https://i.gyazo.com/ae72077621b5f38b71317140fe7cd2f8.png" alt="loaded google.com into web browser and it worked"> </img>

**Comment by DarkShoot06** [comment]
Hi, try this command in your console "Webbrowser 0".
Normaly, it should fix your problem.

**Comment by Cynosphere** [comment]
You want `webbrowser_f1_open 0` as `webbrowser` is not a cvar but a concommand to open the webbrowser.

**Comment by Python1320** [comment]
This now defaults to off.
