### ISSUE TITLE
Breaks ULX

### ISSUE THREAD

**Issue by N7-Yohas** [Metastruct/outfitter#53]
Hey, I'm a Super Admin on a server with ULX. The motd, and ban menu both break, is there a fix so I can send it to the owner?

**Comment by Python1320** [comment]
Do you have an error?

**Comment by N7-Yohas** [comment]
The motd opening causes script errors. The ban menu doesn't, although it is just completely blank.

**Comment by Python1320** [comment]
Please paste the script errors here from developer console.

**Comment by N7-Yohas** [comment]
The owner uses a website, and everytime he uses it, it just goes back to blank. Here's the script error I got:
[ERROR] addons/ulx/lua/ulx/modules/cl/motdmenu.lua:29: bad argument #1 to 'SetHTML' (string expected, got nil)
  1. SetHTML - [C]:-1
   2. fn - addons/ulx/lua/ulx/modules/cl/motdmenu.lua:29
    3. func - addons/ulib/lua/ulib/client/cl_util.lua:22
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by Python1320** [comment]
You seem to have modified motdmenu as I can't find any way for SetHTML to be given nil in https://github.com/TeamUlysses/ulx/blob/master/lua/ulx/modules/cl/motdmenu.lua#L36 and the line numbers are different.

**Comment by N7-Yohas** [comment]
We use the steam workshop version. Could that maybe be why?

**Comment by Python1320** [comment]
The error says it comes from addons/ulx and I was told the workshop file does not have SetHTML on line 29

**Comment by N7-Yohas** [comment]
Okay. Thanks for your time, dude. I'll let the owner know that we have a weird version of ULX.
