### ISSUE TITLE
Some outfits cause players to freeze in place and spawn in frozen when killed by someone using and outfit or when you kill yourself

### ISSUE THREAD

**Issue by Synkstar** [Metastruct/outfitter#55]
This bug is very strange and I heard someone tell me it has to do with outfitter which does make sense. No errors or anything you just either have to rejoin or get an admin to pick you up with a physgun.

**Comment by Python1320** [comment]
Please provide a server where this can be observed.

**Comment by Synkstar** [comment]
My server but someone told me that it happens on other servers with outfitter. Commonly happens when killed by a prop or if you kill yourself in god but not 100% of the time

**Comment by Python1320** [comment]
Fullupdate may be causing long delays where you appear to be frozen. Current solution has no fullupdate any longer. Please reopen if problem still exists.
