### ISSUE TITLE
Playermodel works in singleplayer but doesn't work in multiplayer

### ISSUE THREAD

**Issue by Gmoduser103299** [Metastruct/outfitter#56]
So i was using an addon called Halo reach customizable spartan playermodel  and when i used it in single player, it was working properly. But when i join a server specificaly The sandbox| PVP & Build | Wire, E2,PAC3 ( it will soon be rebranded as gmod3000). Once i joined the server i got an error saying, its has no playermodel. Is there anyway to fix it or no?

**Comment by paz** [comment]
issue with ur server probably man

**Comment by Gmoduser103299** [comment]
Oh okay, that would make sense for why on some servers it works
