### ISSUE TITLE
Ragdoll Support?

### ISSUE THREAD

**Issue by PizzaLawyer420** [Metastruct/outfitter#6]
Do you guys think you will ever add support for rag-doll models? In a similar manner to PAC3 where you can set a rag-doll as your model with bone merge?

**Comment by EgrOnWire** [comment]
It is possible, but not all servers will be willing to install outfitter with pac, they think that outfitter makes more lag than pac3 does.

**Comment by Noiwex** [comment]
What do you mean? You want to use outfitter models on prop_ragdoll?

**Comment by PizzaLawyer420** [comment]
> What do you mean? You want to use outfitter models on prop_ragdoll?

No, using ragdolls **as** playermodels.

**Comment by Python1320** [comment]
This is possible, but at least for me a very low priority feature.

Forcing ragdolls become player models is possible, but very hacky and laggy. Better alternative is to force the model creator spend little more time converting the ragdolls to player models.

**Comment by Python1320** [comment]
Likely does not belong to outfitter as a feature but instead should be its own addon
