### ISSUE TITLE
"Oversize"

### ISSUE THREAD

**Issue by RandomDude11232** [Metastruct/outfitter#62]
I am trying to load an outfit in outfitter and it says "Download failed for workshop 2035519790: oversize", but it works perfectly in the default Player model selector.

**Comment by RandomDude11232** [comment]
Link to the PM: https://steamcommunity.com/sharedfiles/filedetails/?id=2035519790

**Comment by Python1320** [comment]
You can increase limit from settings for maximum filesize. Do remember other players still have 60MB limit.
