### ISSUE TITLE
Outfitter history and autoload not working

### ISSUE THREAD

**Issue by Poliusek** [Metastruct/outfitter#66]
Hello, I'm having issues with my outfitter not saving playermodel autoload and my outfits history. Does anyone know how to fix it?

**Comment by Python1320** [comment]
rename cl.db to something else

**Comment by notallthatslav** [comment]
i did this, and it didnt work for me
the model didnt show up in history

**Comment by notallthatslav** [comment]
the autowear DID work though

**Comment by notallthatslav** [comment]
wait, im just stupid
it showed up it history, sorry for bothering you
