### ISSUE TITLE
Website isnt loading properly

### ISSUE THREAD

**Issue by Minkeyee** [Metastruct/outfitter#68]
The browser that opens doesnt load the background

**Comment by Python1320** [comment]
you mean the background is transparent?

**Comment by Minkeyee** [comment]
> you mean the background is transparent?

yes

**Comment by Minkeyee** [comment]
Now the background is transparent and it only shows that no results were found when i search something

**Comment by Python1320** [comment]
I cannot reproduce this. It works for both x86-64 and normal gmod branch. It loads for a while while it is transparent and then shows the webpage. You can also just paste an url from firefox to the browser url bar and click the select button.
