### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by slaVACo** [Metastruct/outfitter#70]
`-Lua Stack Traces-
  Client
    0. SetModel - [C]:-1
      1. Enforce - addons/[script] outfitter/lua/outfitter/cl_util.lua:302
        2. StartEnforcing - addons/[script] outfitter/lua/outfitter/cl_util.lua:325
          3. EnforceModel - addons/[script] outfitter/lua/outfitter/cl_util.lua:364
            4. SET - addons/[script] outfitter/lua/outfitter/cl.lua:30
              5. ChangeOutfitThreadWorker - addons/[script] outfitter/lua/outfitter/cl.lua:228
                6. func - addons/[script] outfitter/lua/outfitter/cl.lua:130
                  7. (null) - addons/[script] outfitter/lua/includes/modules/co.lua:218

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*

-Console Buffer-
================
11620(15157.350305):  -------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x39E) : invalid handle, not in dictionary (of size 1579).
-------------------------------------------------------------------------------
11619(15157.350286):  -------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x39E) : invalid handle, not in dictionary (of size 1579).
-------------------------------------------------------------------------------
11618(15157.350279):  -------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x39E) : invalid handle, not in dictionary (of size 1579).
-------------------------------------------------------------------------------
11617(15157.350274):  -------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x39E) : invalid handle, not in dictionary (of size 1579).
-------------------------------------------------------------------------------
11616(15157.350254):  -------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x39E) : invalid handle, not in dictionary (of size 1579).
-------------------------------------------------------------------------------
11615(15157.350231):  -------------------------------------------------------------------------------
CMDLCache::GetStudioHdr(0x39E) : invalid handle, not in dictionary (of size 1579).
-------------------------------------------------------------------------------`

**Comment by Python1320** [comment]
Cannot fix.
