### ISSUE TITLE
Complex Gamebreaking Problem Involving Crashes

### ISSUE THREAD

**Issue by Kishiyaki** [Metastruct/outfitter#71]
when picking an outfit, if your game crashes once it loads or close to after it loads, you can no longer select the outfit again and doing so results an error message containing this pop up

[OF ERROR] @lua/outfitter/cl.lua:25: EnforceModel CRASH models/player/ [PLAYERMODEL HERE] 2155711793
stack traceback:
lua/outfitter/cl.lua:25: in function 'SET'
lua/outfitter/cl.lua:184: in function 'ChangeOutfitThreadWorker'
lua/outfitter/cl.lua:130: in function 'func'
lua/includes/modules/co.lua:218: in function <lua/includes/modules/co.lua:217>
[OF ERROR] @lua/outfitter/cl.lua:186: DoChangeOutfit Setting model failed, but file.Existed crash models/player/ [PLAYERMODEL HERE]
stack traceback:
lua/outfitter/cl.lua:186: in function 'ChangeOutfitThreadWorker'
lua/outfitter/cl.lua:130: in function 'func'
lua/includes/modules/co.lua:218: in function <lua/includes/modules/co.lua:217>

recently this problem has now affected 3 of my available outfitter outfits, making them unusable.

and no, redownloading the mod does not infact help, i've tried twice now

if this starts affecting my entire library of outfits the mod will be completely unusable and irrelevant

**Comment by Python1320** [comment]
Run in console outfitter_blacklist_clear. I will add a message to do this or to disable the blacklist feature. It's to protect from outfits that would be constantly crashing players to grief everyone.
