### ISSUE TITLE
Nevertstopping Finished/Mounted on the bottom left of the screen.

### ISSUE THREAD

**Issue by GJungle1** [Metastruct/outfitter#75]
https://i.imgur.com/mfGIoU8.png
Screen shot of outfitter_dbg 10

**Comment by GJungle1** [comment]
![mfGIoU8](https://user-images.githubusercontent.com/54341728/124033449-ce15bc80-d9ae-11eb-902e-cab0870212a9.png)

**Comment by Python1320** [comment]
Possibly fixed. Reopen if still problem
