### ISSUE TITLE
Animations appears broken when weapon is equipped

### ISSUE THREAD

**Issue by sr229** [Metastruct/outfitter#76]
Not sure if this is a bug within my client (I have CS:S, HL2 (E1 and E2), TF2 and CSGO mounted) but some models have broken animations when ran on third person.

https://user-images.githubusercontent.com/14976516/129445081-4b94f3f8-359f-42da-b58a-65553ed01438.mov

**Comment by Python1320** [comment]
Does this happen in singleplayer

**Comment by sr229** [comment]
I've tested on SP and I couldn't get a concrete answer: sometimes it does, sometimes it doesn't, which makes it hard to triage.

**Comment by Python1320** [comment]
Please post the outfit name then so I can test

**Comment by sr229** [comment]
> Please post the outfit link then so I can test. You must also have closed gmod and started to have a clean state.


Here is the [Workshop link](https://steamcommunity.com/sharedfiles/filedetails/?id=2295983588) for the one I used for this test.

**Comment by sr229** [comment]
Did some extended testing I was able to conclude:

* Behavior is more stable in Singleplayer and P2P Multiplayer, animations wouldn't break.
* However, connecting to Metastruct under high lerp will cause the animations to break at one point, but this behavior is inconsistent
* A very rare case to happen is when you kill yourself while outfitter is changing your playermodel will end up with broken animations or a missing viewmodel (though that's a seperate issue).

So the addon itself might not be "broken", but it can be "broken" when joining Metastruct on high lerp.

**Comment by sr229** [comment]
Looks like this no longer persists. Closing as fixed.
