### ISSUE TITLE
Playermodel spawning at world origin

### ISSUE THREAD

**Issue by magicdog2013games** [Metastruct/outfitter#79]
Some models will just spawn at the world origin and leave me invisible

**Comment by Cynosphere** [comment]
Any specific models that could be used to replicate?

**Comment by magicdog2013games** [comment]
This one specifically: https://steamcommunity.com/sharedfiles/filedetails/?id=2556481050 
not sure what's causing it

**Comment by magicdog2013games** [comment]
> Any specific models that could be used to replicate?

This one specifically: https://steamcommunity.com/sharedfiles/filedetails/?id=2556481050 not sure what's causing it. It's my addon but I commissioned someone to make it and they don't know what outfitter is so I don't know what to do

**Comment by Python1320** [comment]
![image](https://user-images.githubusercontent.com/207340/162076793-af8806e6-6e6f-4f2a-92da-54351faffe4e.png)
It looks like the playermodel is supremely messed up even in model viewer with wrong bone names and I can't even get the model to appear in the model viewer, but I could replicate it drawing in world origin at least. Outfitter does nothing particularly special and there is likely nothing I can do to "fix" this.
