### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Be1zebub** [Metastruct/outfitter#83]
pls pull eedcbc105c4514c2e9151c309f65bff33dbd32f7 commit into workshop
skin values out of 0-2^32 range causes crash
https://developer.valvesoftware.com/wiki/$texturegroup#:~:text=Even%20though%20studiomdl%20has%20a%20hardcoded%20limit%20of%2032%20unique%20materials%2C%20it%20technically%20supports%20up%20to%201024%20total%20skins%2C%20so%20long%20as%20each%20skin%20is%20an%20arrangement%20of%20those%2032%20materials.
skin value cant be more then 1024 because its hardcoded in studiomdl, so you should also replace `net.Write/ReadUInt(32)` with `net.Write/ReadUInt(10)`

**Comment by Be1zebub** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/5275

**Comment by SpiffyJUNIOR** [comment]
fixed in gmod's dev branch, should this issue be closed?

**Comment by Be1zebub** [comment]
i think in any way it should be merged, because 32 bits unit with math.Clamp is useless

**Comment by Python1320** [comment]
Thank you and sorry, spam me on discord in the future to update things promptly. I will try to get workshop up to date asap even if this is no longer that necessary.
