### ISSUE TITLE
 Parsing workshop addon failed: 4gbfile

### ISSUE THREAD

**Issue by atmogenic** [Metastruct/outfitter#87]
I want to use this addon model  2570101454 but i'm getting an error saying 4gbfile, I checked the model size and it's 35mb and my max size limit on my outfitter is at 60mb, I've also tried putting it to the max at 256 but i'm still getting the error to that playermodel

**Comment by Python1320** [comment]
Will try to check this soon

**Comment by atmogenic** [comment]
is this still being checked on?

**Comment by Python1320** [comment]
Should be fixed now (test on g2.metastruct.net). Uploading next week to workshop.

**Comment by atmogenic** [comment]
> Should be fixed now (test on g2.metastruct.net). Uploading next week to workshop.

ok that is good to help thanks
