### ISSUE TITLE
A REC thing at the top right of my screen

### ISSUE THREAD

**Issue by DFO627** [Metastruct/outfitter#89]
So I found out oufitter is the reason this strange thing pops up at the top right of my screen, it says "REC" And is really annoying, and I'm a bit paranoid about it...
![Screenshot (432)](https://user-images.githubusercontent.com/126930401/233548525-f16d0fc7-0914-4cda-856d-450630acc1d9.png)

**Comment by notsokodya** [comment]
I don't think this is outfitter issue, because that [rec] thing appear during demo record

**Comment by notsokodya** [comment]
"demostop" or "gm_demo_icon 0" if you want just hide icon instead stopping demo record
