### ISSUE TITLE
Identically Named Playermodels

### ISSUE THREAD

**Issue by mikyoupon** [Metastruct/outfitter#9]
It seems that playermodels with the same directory are replacing one another, i.e. if one player selects a model and then a second player selects a different model by the same name, the second player's model will become the first player's. I've only found one case of this happening and that's between these two models:

http://steamcommunity.com/sharedfiles/filedetails/?id=158777498
http://steamcommunity.com/sharedfiles/filedetails/?id=312501431

**Comment by PotcFdk** [comment]
Hmm, they might be sharing the same model path. Can anyone check?

**Comment by notcake** [comment]
@Python1320 PLS PARSE AND REWRITE THE GMA TO HAVE UNIQUE PATHS

**Comment by Python1320** [comment]
@PotcFdk yep, the models have same paths.

Rewriting model paths is too error prone to be worth the hassle. This is expected behaviour. Which model should remain is up for debate, though.
