### ISSUE TITLE
Other players can't see playermodel

### ISSUE THREAD

**Issue by rivercabbage** [Metastruct/outfitter#92]
So I'm playing on the server called: {LGB}sandbox and when I try on a pm everything is fine When I even go into third person (the sever has a third person mod) my pm is correct but people on the server cannot see my pm instead thay see just the default pm (a blue combine)

the pm I'm trying to use: https://steamcommunity.com/sharedfiles/filedetails/?id=2010827306&searchtext=Steven+Universe

the other one im trying to use: https://steamcommunity.com/sharedfiles/filedetails/?id=1384638879&searchtext=Steven+Universe

it works for me
![20230830160032_1](https://github.com/Metastruct/outfitter/assets/143654112/5d96d4b6-c7aa-43ba-8576-ccb770a8904a)

but not to anyone else (look at the text)
![20230830160126_1](https://github.com/Metastruct/outfitter/assets/143654112/d04348f2-eb7f-4877-abfd-194be37996a3)

(side note) I suspect it could be the client and not the server. also, the c_hands work too.

please help

-rivercabbage

**Comment by Darkita162** [comment]
You are submitting the outfit, right? I would also recommend setting it to be persistent between logins

**Comment by rivercabbage** [comment]
> You are submitting the outfit, right? I would also recommend setting it to be persistent between logins

so when you mean submitting the outfit do you mean this: 
![20230831080712_1](https://github.com/Metastruct/outfitter/assets/143654112/902c6d4f-c61b-4694-a06c-57c04113f645)

**Comment by rivercabbage** [comment]
Also sorry for the late response

**Comment by Darkita162** [comment]
> > You are submitting the outfit, right? I would also recommend setting it to be persistent between logins
> 
> so when you mean submitting the outfit do you mean this: ![20230831080712_1](https://user-images.githubusercontent.com/143654112/264639926-902c6d4f-c61b-4694-a06c-57c04113f645.jpg)

Correct. Click that and it should send the playermodel server side instead of client side.

**Comment by rivercabbage** [comment]
> > > You are submitting the outfit, right? I would also recommend setting it to be persistent between logins
> > 
> > 
> > so when you mean submitting the outfit do you mean this: ![20230831080712_1](https://user-images.githubusercontent.com/143654112/264639926-902c6d4f-c61b-4694-a06c-57c04113f645.jpg)
> 
> Correct. Click that and it should send the playermodel server side instead of client side.

ok ill test it out and thank you so so much for providing me the potential answer. thank you

**Comment by rivercabbage** [comment]
so it didn't work? I asked someone if my PM was a combine and they said yes (I had on a different PM)

So I'm just going to show you how I do it

step 1 i open the outfiter mod:
![20230831103057_1](https://github.com/Metastruct/outfitter/assets/143654112/c83d04fe-e076-4962-b480-a2d92721131e)


step 2 I click on open workshop:
![20230831103106_1](https://github.com/Metastruct/outfitter/assets/143654112/19ae315c-1140-4e4e-bcd6-ad72a8641a97)


step 3 I paste the URL of the PM I want In this case it is a pack of PMs Then I hit select character:
![20230831103121_1](https://github.com/Metastruct/outfitter/assets/143654112/4eb764d1-a22f-4a74-9f55-fe0376f37f30)

step 4 loads normally:
![20230831103129_1](https://github.com/Metastruct/outfitter/assets/143654112/102dd309-cf6c-4f57-9fab-5350064005b1)

step 5 I click on the PM I want:
![20230831103135_1](https://github.com/Metastruct/outfitter/assets/143654112/c23b656a-7bdc-40ad-97a7-b23722137c8d)

step 6 (I would normally stop at step 5 but you said to submit it so this is a new step) I click submit:
![20230831103147_1](https://github.com/Metastruct/outfitter/assets/143654112/934b9312-e246-4a0e-9a5a-20d8a40b600d)

pls tell me if anything is out of place or just give some advice

**Comment by rivercabbage** [comment]
also here are my settings:
![20230831104638_1](https://github.com/Metastruct/outfitter/assets/143654112/077d9f35-7218-40d7-ad56-5aab0d92413a)

**Comment by rivercabbage** [comment]
also maybe that is a console command like idk:   enable_outfitter 1   or something?

**Comment by rivercabbage** [comment]
please help

**Comment by Python1320** [comment]
They are restricting PAC3 on the server to donators ( https://subs.lbgaming.co/store.php?page=packages&id=12 ), are you sure they are not just restricting outfitter in addition?

**Comment by rivercabbage** [comment]
> They are restricting PAC3 on the server to donators ( https://subs.lbgaming.co/store.php?page=packages&id=12 ), are you sure they are not just restricting outfitter in addition?

no, I am fairly sure they don't restrict the outfitter. because one of the lowest ranks a player can have on the server is a spammer rank. it can still use the mod and I'm a member rank. (two ranks above the spammer rank) Even the user rank (a rank below mine) can still use an outfitter. (Also if a player buys one of the packs they will have a premium rank I have only seen one rank like that)

and if they do for some reason restrict it it won't even allow me to click on it. because PAC3 would just put me on the page where you could buy one of the packs. (to get the PAC3 and other things)

**Comment by rivercabbage** [comment]
also when somebody else puts on a skin I can see the outfit downloading icon (at the bottom of the screen) but when I do it it still makes the noize but I can't see the download icon.

pls respond and thanks for helping

the downloading icon I'm referring to: 
![20230908160157_1](https://github.com/Metastruct/outfitter/assets/143654112/ad37993e-a21f-468a-871e-c00340b97808)

**Comment by Earu** [comment]
Have you made sure your player model is not above the size limit for other players?

**Comment by rivercabbage** [comment]
> Have you made sure your player model is not above the size limit for other players?

So the first pack is this one: https://steamcommunity.com/sharedfiles/filedetails/?id=2010827306&searchtext=Steven+Universe 
It is a pretty heavy one (218.966 MB) but at the same time it is a pack of PMs so idk if I pick only one PM It only does the Pacific download from the one I picked from the pack. or it just downloads the whole pack and some people can't download it because their default downloading size is too small.

but another one I'm trying to do is this one: https://steamcommunity.com/sharedfiles/filedetails/?id=1384638879&searchtext=Steven+Universe
This one is relatively light (only 1.277 MB)

I have tried the 1 MB one and still nothing. but I do suspect it could be my default download size that could conflict with the downloading?.....ya idk

(Thanks for responding)

**Comment by Earu** [comment]
The default size is 60mb:
![image](https://github.com/Metastruct/outfitter/assets/20880060/cc843289-4c19-4dc6-b3d1-6976a81d3d9c)

Players probably cant see your playermodel because its too big.

**Comment by Python1320** [comment]
Until we have outfitter accelerator or rubat makes workshop decompression asynchronous I will not raise the limit since the freeze from mounting large addons is insanely long

**Comment by Python1320** [comment]
If you have a problem with 1384638879 come join metastruct and ask people around if they can see your outfit so we  can narrow down the server limiting outfits.
